import type { NextPage } from "next";
import NextHead from "next/head";
import Link from "next/link";
import { Dropzone } from "../components/Dropzone";
import { Gallery } from "../components/Gallery";

const Home: NextPage = () => {
  const pageTitle =
    "ujc to png | Export, convert and save your puzzle designs from Nonograms Katana as simple png images";
  const pageDescription =
    "Export, convert and save your ujc puzzle designs from Nonograms Katana as simple png images";

  return (
    <>
      <NextHead>
        <title>{pageTitle}</title>
        <meta name="description" content={pageDescription} />

        <meta property="og:title" content={pageTitle} />
        <meta property="og:description" content={pageDescription} />
        <meta property="og:url" content="https://ujc-to-png.vercel.app/" />

        <meta property="twitter:title" content={pageTitle} />
        <meta property="twitter:description" content={pageDescription} />

        {process.env.NODE_ENV === "production" &&
          typeof window !== "undefined" && (
            <script
              async
              defer
              data-domain="ujc-to-png.vercel.app"
              src="https://plausible.io/js/plausible.outbound-links.js"
            />
          )}
      </NextHead>

      <div className="mx-auto max-w-screen-lg space-y-8 px-4 sm:px-8">
        <section className="mt-8 space-y-4">
          <h1 className="text-center text-4xl">ujc to png</h1>
          <p className="px-4 text-center text-lg sm:px-12 md:px-28 lg:px-64">
            Export, convert and save your puzzle designs from{" "}
            <a
              className="underline"
              href="https://play.google.com/store/apps/details?id=com.ucdevs.jcross"
            >
              Nonograms Katana
            </a>{" "}
            as simple png images.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl">Usage</h2>
          <p>
            With this tool, nonogram authors can convert their own designs from
            the <span className="font-mono">.ujc</span> files generated by the
            app to standard <span className="font-mono">.png</span> images.
          </p>
          <p>
            To start, open the Nonograms Katana app, then tap on the settings
            icon in the top right corner; once in the settings, open the
            sub-menu named <span className="font-mono italic">Other</span> and
            select{" "}
            <span className="font-mono italic">
              Save progress to file (zip)
            </span>{" "}
            to export an archive of your data.
          </p>
          <p>
            Using your preferred file manager, extract the{" "}
            <span className="font-mono italic">NonogramsKatana.zip</span>{" "}
            archive so that the sub-folder named{" "}
            <span className="font-mono italic">MyNonograms</span> becomes
            accessible. This folder contains all the nonograms created by you
            saved as <span className="font-mono">.ujc</span> files.
          </p>
          <p>
            Now, you can drag and drop these files in the area below;
            alternatively, you can click or tap on the area to open a dialog
            where you can select <span className="font-mono">.ujc</span> files.
            The converted images will appear in the gallery below.
          </p>
        </section>

        <section>
          <Dropzone />
        </section>

        <section>
          <h2 className="text-2xl">Your Nonograms</h2>
          <Gallery />
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl">FAQ</h2>

          <div className="space-y-2">
            <h3 className="text-lg">How does this work?</h3>
            <p>
              This tool analyzes the <span className="font-mono">.ujc</span>{" "}
              files exported from Nonograms Katana and extracts the png images
              representing the nonogram designs; to learn more, you can review
              the source code{" "}
              <a
                className="underline"
                href="https://github.com/velut/ujc-to-png"
              >
                available on GitHub
              </a>
              .
            </p>
          </div>

          <div className="space-y-2">
            <h3 className="text-lg">Who is this for?</h3>
            <p>
              This tool is aimed at nonogram authors that want to backup their
              own designs and have them available as images.
            </p>
          </div>

          <div className="space-y-2">
            <h3 className="text-lg">Are my nonograms private?</h3>
            <p>
              Yes. The tool works entirely in your browser and no file ever
              leaves your device.
            </p>
          </div>

          <div className="space-y-2">
            <h3 className="text-lg">
              Can I download nonograms from other authors?
            </h3>
            <p>No. This tool does not download nonograms from the app.</p>
          </div>

          <div className="space-y-2">
            <h3 className="text-lg">How many nonograms can I convert?</h3>
            <p>
              Right now there is no limit. Note however that the more nonograms
              you select the slower the process will be, especially on less
              powerful devices.
            </p>
          </div>

          <div className="space-y-2">
            <h3 className="text-lg">
              Why nothing happens after I select the{" "}
              <span className="font-mono">.ujc</span> files?
            </h3>
            <p>
              On less powerful devices, the conversion process can take a few
              seconds. Either wait a little before retrying or convert fewer
              nonograms at a time.
            </p>
          </div>

          <div className="space-y-2">
            <h3 className="text-lg">
              Why do some images have transparent backgrounds?
            </h3>
            <p>
              The background color of colored nonograms is currently saved as
              transparent.
            </p>
          </div>

          <div className="space-y-2">
            <h3 className="text-lg">
              I found an error / I want to ask another question.
            </h3>
            <p>
              Please{" "}
              <a
                className="underline"
                href="https://github.com/velut/ujc-to-png/issues"
              >
                open an issue on Github
              </a>
              .
            </p>
          </div>
        </section>

        <div>
          <footer className="mt-12 border-t border-gray-500 py-6">
            <p>
              Website by{" "}
              <a
                className="underline"
                href="https://twitter.com/EdoardoScibona"
              >
                Edoardo Scibona
              </a>
            </p>

            <div className="mt-4 flex flex-wrap gap-4">
              <Link href="/privacy">
                <a className="underline">Privacy Policy</a>
              </Link>

              <a
                className="underline"
                href="https://github.com/velut/ujc-to-png"
              >
                GitHub
              </a>
            </div>
          </footer>
        </div>
      </div>
    </>
  );
};

export default Home;
