import type { NextPage } from "next";
import dynamic from "next/dynamic";
import Link from "next/link";
import { Dropzone } from "../components/Dropzone";

const Gallery = dynamic(
  () => import("../components/Gallery").then(({ Gallery }) => Gallery as any),
  { ssr: false }
);

const Home: NextPage = () => {
  return (
    <div className="mx-auto max-w-screen-lg space-y-8 px-4 sm:px-8">
      <section className="mt-8 space-y-4">
        <h1 className="text-center text-4xl">ujc to png</h1>
        <p className="px-4 text-center text-lg sm:px-12 md:px-28 lg:px-64">
          Export, convert and save your puzzle designs from{" "}
          <a
            className="underline"
            href="https://play.google.com/store/apps/details?id=com.ucdevs.jcross"
          >
            Nonograms Katana
          </a>{" "}
          as simple <span className="font-mono">.png</span> images.
        </p>
      </section>

      <section className="space-y-4">
        <h2 className="text-2xl">Usage</h2>
        <p>
          With this tool, nonogram authors can convert their own designs from
          the <span className="font-mono">.ujc</span> files generated by the app
          to standard <span className="font-mono">.png</span> images.
        </p>
        <p>
          To start, open the Nonograms Katana app, then tap on the settings icon
          in the top right corner; once in the settings, open the sub-menu named{" "}
          <span className="font-mono italic">Other</span> and select{" "}
          <span className="font-mono italic">Save progress to file (zip)</span>{" "}
          to export an archive of your data.
        </p>
        <p>
          Using your preferred file manager, extract the{" "}
          <span className="font-mono italic">NonogramsKatana.zip</span> archive
          so that the sub-folder named{" "}
          <span className="font-mono italic">MyNonograms</span> becomes
          accessible. This folder contains all the nonograms created by you
          saved as <span className="font-mono">.ujc</span> files.
        </p>
        <p>
          Now, you can drag and drop these files in the area below;
          alternatively, you can click or tap on the area to open a dialog where
          you can select <span className="font-mono">.ujc</span> files. The
          converted images will appear in the gallery below.
        </p>
      </section>

      <section>
        <Dropzone />
      </section>

      <section>
        <h2 className="text-2xl">Your Nonograms</h2>
        <Gallery />
      </section>

      <div>
        <footer>
          <Link href="/privacy">
            <a className="underline">Privacy Policy</a>
          </Link>
        </footer>
      </div>
    </div>
  );
};

export default Home;
