import Link from "next/link";

export default function FAQ() {
	return (
		<div>
			<h2>FAQ</h2>

			<ul>
				<li>
					<p>
						<strong>How does this tool work?</strong>
					</p>
					<p>
						This tool analyzes the <code>.ujc</code> files generated by the app and extracts the
						contained png images that represent the nonogram pictures.
					</p>
					<p>
						To learn more, you can review the{" "}
						<Link href="https://github.com/velut/ujc-to-png">source code available on GitHub</Link>.
					</p>
				</li>
				<li>
					<p>
						<strong>Who is this tool for?</strong>
					</p>
					<p>
						This tool is for nonogram authors who want to backup their own designs and have them
						available as images.
					</p>
				</li>
				<li>
					<p>
						<strong>Are my nonograms private?</strong>
					</p>
					<p>
						<strong>Yes</strong>. This tool works entirely inside your browser and no file ever
						leaves your device.
					</p>
				</li>
				<li>
					<p>
						<strong>Can I download nonograms made by other authors?</strong>
					</p>
					<p>
						<strong>No</strong>. To respect their work, this tool does not allow you to download
						nonograms made by other authors.
					</p>
				</li>
				<li>
					<p>
						<strong>How many nonograms can I convert?</strong>
					</p>
					<p>
						As many as you want. Note, however, that the more nonograms you process together the
						slower the conversion will be, especially on less powerful devices.
					</p>
				</li>
				<li>
					<p>
						<strong>
							Why does nothing happen after I select the
							<code>.ujc</code> files?
						</strong>
					</p>
					<p>
						On less powerful devices, the conversion process can take a few seconds or more. Either
						wait a little before retrying or convert fewer nonograms at a time.
					</p>
				</li>
				<li>
					<p>
						<strong>Why do some images have transparent backgrounds?</strong>
					</p>
					<p>
						When the <code>Recolor images</code> option is not selected, images are extracted as-is
						from the <code>.ujc</code> files, which internally represent the background color of
						colored nonograms as transparent.
					</p>
					<p>
						To fix the final colors, enable the <code>Recolor images</code> option. Note, however,
						that due to{" "}
						<Link href="https://html.spec.whatwg.org/multipage/canvas.html#dom-context-2d-getimagedata">
							the way that browsers work
						</Link>{" "}
						, this is a lossy operation and the final colors may be slightly different from the
						original ones you selected in the app editor.
					</p>
				</li>
				<li>
					<p>
						<strong>Why are the extracted images so small?</strong>
					</p>
					<p>
						If the <code>Scale images</code> option is set to <code>1</code>, the final image
						dimensions correspond to the original dimensions of the nonogram. For example, a 20x20
						nonogram becomes a tiny 20x20 pixels image.
					</p>
					<p>
						To save images in a larger format, increase the value of the <code>Scale images</code>{" "}
						option. For example, scaling a 20x20 nonogram by a value of <code>25</code> produces a
						larger 500x500 pixels image, since <code>20*25 = 500</code>.
					</p>
					<p>
						Note that, similarly to the <code>Recolor images</code> option, this is a lossy
						operation and the final colors may be slightly different from the original ones you
						selected in the app editor.
					</p>
				</li>
				<li>
					<p>
						<strong>
							Why does the <code>Border radius</code> option not work?
						</strong>
					</p>
					<p>
						Make sure you are using the latest version of a supported browser and try increasing
						both the <code>Scale images</code> option and the <code>Border radius</code> option to a
						high value like <code>50</code> to verify that it works.
					</p>
				</li>
				<li>
					<p>
						<strong>
							Why are the <code>Dropzone</code>, <code>Options</code>, and <code>Gallery</code>{" "}
							sections not visible?
						</strong>
					</p>
					<p>
						This can happen when something goes wrong when loading the tool. Make sure you are using
						an updated and supported browser that has Javascript enabled and try reloading the page.
					</p>
				</li>
				<li>
					<p>
						<strong>Can I directly import png images into this tool?</strong>
					</p>
					<p>
						<strong>Yes</strong>. Just drag and drop them into the dropzone or select them in the
						file picker. After that you can manipulate them as usual with the available options. For
						example, you can use this tool to add pixel grid lines to your pixel art image.
					</p>
				</li>
				<li>
					<p>
						<strong>Can I save my nonograms from the Nonograms Katana iOS app?</strong>
					</p>
					<p>
						<strong>No</strong>. Unfortunately, the Android and iOS versions of the Nonograms Katana
						app are different and the iOS version does not currently provide an option to export
						your nonograms to a local file.
					</p>
					<p>
						If you find a way to export or share <code>.ujc</code> files from the iOS app, please
						open an issue (see last question) so that we can update this answer.
					</p>
				</li>
				<li>
					<p>
						<strong>I found an error / I want to ask another question.</strong>
					</p>
					<p>
						Please{" "}
						<Link href="https://github.com/velut/ujc-to-png/issues">open an issue on Github</Link>,
						it&apos;s the fastest way to have your question seen.
					</p>
				</li>
			</ul>
		</div>
	);
}
