name: CI for main branch

on:
  push:
    branches:
      - "main"

jobs:
  # See https://stackoverflow.com/a/73624365/16109047
  build:
    runs-on: ubuntu-latest
    if: github.repository == 'velut/ujc-to-png' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup bun
        uses: oven-sh/setup-bun@v2

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: lts/*

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Lint
        run: bun run lint

      - name: Build
        run: bun run build
