name: CI for main branch

on:
  push:
    branches:
      - "main"

jobs:
  # See https://stackoverflow.com/a/73624365/16109047
  build-and-deploy:
    runs-on: ubuntu-latest
    if: github.repository == 'velut/ujc-to-png' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm lint

      - name: Build
        run: pnpm build
